# Generated by Django 3.0.2 on 2020-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_email',
            field=models.EmailField(default=11111, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='full_name',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
