# Generated by Django 3.0.2 on 2020-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200204_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submit',
            field=models.CharField(default=11111, max_length=200),
            preserve_default=False,
        ),
    ]
