# Generated by Django 3.0.1 on 2020-01-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_recipe_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
