# Generated by Django 3.0.1 on 2020-01-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200127_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipes',
        ),
    ]
