# Generated by Django 3.0.1 on 2020-01-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_comment_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(to='main.Comment'),
        ),
    ]
