# Generated by Django 3.0.1 on 2020-01-29 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recipe_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.AddField(
            model_name='comment',
            name='cr_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='flag',
            field=models.CharField(blank=True, choices=[('apple', 'apple'), ('mango', 'mango')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.TextField()),
                ('member_address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(default=223, on_delete=django.db.models.deletion.CASCADE, to='main.Member'),
            preserve_default=False,
        ),
    ]
