# Generated by Django 3.0.1 on 2020-01-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200129_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
    ]
