# Generated by Django 3.0.1 on 2020-01-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200129_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
