# Generated by Django 3.0.1 on 2020-01-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
