# Generated by Django 3.0.2 on 2020-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_recipe_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.FileField(default=1111, upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
