# Generated by Django 3.0.2 on 2020-02-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
