# Generated by Django 3.0.2 on 2020-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_video',
            name='name',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
    ]
