# Generated by Django 3.0.2 on 2020-02-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_download', '0002_recipe_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_video',
            name='videos',
            field=models.FileField(null=True, upload_to='recipe_videos/', verbose_name=''),
        ),
    ]
